name: CI

on:
  pull_request: ~
  push:
    branches: [main]
  workflow_dispatch: ~

permissions:
  contents: read
  actions: read

jobs:

  linux:
    name: Linux
    uses: sanko/workflow-testing/.github/workflows/run-direct.yml@main
    secrets: inherit
    with:
      task: |
        perl -V
        perl hello.pl
      matrix: >
        [
          {"platform_name":"ubuntu","os":"ubuntu-latest","arch":"x86_64","toolchain":"gcc","perl_version":"5.40.5"},
          {"platform_name":"ubuntu","os":"ubuntu-latest","arch":"x86_64","toolchain":"gcc","perl_version":"5.42.3","configure":"-Duselongdouble","variant":"longdoubles"}
        ]

  macos:
    name: macOS
    uses: sanko/workflow-testing/.github/workflows/run-direct.yml@main
    secrets: inherit
    with:
      task: |
        perl -V
        perl hello.pl
      matrix: >
        [
          {"platform_name":"macos","os":"macos-15","arch":"aarch64","toolchain":"gcc","perl_version":"5.42.3"}
        ]

  windows:
    name: Windows
    uses: sanko/workflow-testing/.github/workflows/run-direct.yml@main
    secrets: inherit
    with:
      task: |
        perl -V
        perl hello.pl
      matrix: >
        [
          {"platform_name":"windows","os":"windows-latest","arch":"x86_64","toolchain":"gcc","prepare":"choco install strawberryperl"}
        ]

  freebsd:
    name: FreeBSD
    uses: sanko/workflow-testing/.github/workflows/run-vm.yml@main
    secrets: inherit
    with:
      os_version: '15.0'
      task: |
        perl -V
        perl hello.pl
      matrix: >
        [
          {"platform_name":"freebsd","os":"freebsd","arch":"x86_64","toolchain":"clang","prepare":"pkg install -y gmake","perl_version":"5.40.5"}
        ]

  results:
    name: Summary
    if: always()
    needs: [linux, macos, windows, freebsd]
    uses: sanko/workflow-testing/.github/workflows/results-summary.yml@main
